# Generated by Django 4.2.10 on 2024-02-07 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('quarter_id', models.AutoField(primary_key=True, serialize=False)),
                ('quarter_name', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name_plural': 'Quarters',
                'unique_together': {('quarter_name',)},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=256)),
                ('version', models.CharField(max_length=20)),
                ('custom', models.BooleanField(default=False)),
                ('abstract', models.BooleanField(default=False)),
                ('data_type', models.CharField(blank=True, max_length=20, null=True)),
                ('iord', models.CharField(blank=True, max_length=1, null=True)),
                ('crdr', models.CharField(blank=True, max_length=1, null=True)),
                ('tlabel', models.CharField(blank=True, max_length=512, null=True)),
                ('doc', models.TextField(blank=True, null=True)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_quarter', to='reports.quarter')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'unique_together': {('tag_name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('adsh', models.CharField(max_length=20)),
                ('cik', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('sic', models.SmallIntegerField(null=True)),
                ('countryba', models.CharField(max_length=2)),
                ('stprba', models.CharField(max_length=2, null=True)),
                ('cityba', models.CharField(max_length=30)),
                ('zipba', models.CharField(max_length=10, null=True)),
                ('bas1', models.CharField(max_length=40, null=True)),
                ('bas2', models.CharField(max_length=40, null=True)),
                ('baph', models.CharField(max_length=20, null=True)),
                ('countryma', models.CharField(max_length=2, null=True)),
                ('stprma', models.CharField(max_length=2, null=True)),
                ('cityma', models.CharField(max_length=30, null=True)),
                ('zipma', models.CharField(max_length=10, null=True)),
                ('mas1', models.CharField(max_length=40, null=True)),
                ('mas2', models.CharField(max_length=40, null=True)),
                ('countryinc', models.CharField(max_length=3)),
                ('stprinc', models.CharField(max_length=2, null=True)),
                ('ein', models.IntegerField(null=True)),
                ('former', models.CharField(max_length=150, null=True)),
                ('changed', models.CharField(max_length=8, null=True)),
                ('afs', models.CharField(max_length=5, null=True)),
                ('wksi', models.BooleanField(default=False)),
                ('fye', models.CharField(max_length=4)),
                ('form', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=8)),
                ('fy', models.CharField(max_length=4)),
                ('fp', models.CharField(max_length=2)),
                ('filed', models.CharField(max_length=8)),
                ('accepted', models.CharField(max_length=19)),
                ('prevrpt', models.BooleanField(default=False)),
                ('detail', models.BooleanField(default=False)),
                ('instance', models.CharField(max_length=32)),
                ('nciks', models.SmallIntegerField()),
                ('aciks', models.CharField(max_length=120, null=True)),
            ],
            options={
                'verbose_name_plural': 'Submissions',
                'unique_together': {('adsh',)},
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('presentation_id', models.AutoField(primary_key=True, serialize=False)),
                ('adsh', models.CharField(max_length=20)),
                ('report', models.IntegerField()),
                ('line', models.IntegerField()),
                ('stmt', models.CharField(max_length=2)),
                ('inpth', models.BooleanField(default=False)),
                ('rfile', models.CharField(max_length=1)),
                ('version', models.CharField(max_length=20)),
                ('plabel', models.CharField(max_length=512)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_tag', to='reports.tag')),
            ],
            options={
                'verbose_name_plural': 'Presentations',
                'unique_together': {('adsh', 'report', 'line')},
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('number_id', models.AutoField(primary_key=True, serialize=False)),
                ('adsh', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('ddate', models.CharField(max_length=8)),
                ('qtrs', models.SmallIntegerField(default=0)),
                ('uom', models.CharField(max_length=20)),
                ('coreg', models.IntegerField(default=0, null=True)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=28, null=True)),
                ('footnote', models.CharField(max_length=512, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_tag', to='reports.tag')),
            ],
            options={
                'verbose_name_plural': 'Numbers',
                'unique_together': {('adsh', 'tag', 'version', 'ddate', 'qtrs', 'uom', 'coreg')},
            },
        ),
    ]
